//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WP_to_WP.International {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WP_to_WP.International.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sobre.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categorias.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to criada por.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajude-nos a corrigir este erro enviando-o por email.
        /// </summary>
        public static string Diagnostics_MessageBox_Content {
            get {
                return ResourceManager.GetString("Diagnostics_MessageBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro.
        /// </summary>
        public static string Diagnostics_MessageBox_Title {
            get {
                return ResourceManager.GetString("Diagnostics_MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to destaques.
        /// </summary>
        public static string Highlights {
            get {
                return ResourceManager.GetString("Highlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancelar.
        /// </summary>
        public static string MBCancelText {
            get {
                return ResourceManager.GetString("MBCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to não.
        /// </summary>
        public static string MBNoText {
            get {
                return ResourceManager.GetString("MBNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sim.
        /// </summary>
        public static string MBOkText {
            get {
                return ResourceManager.GetString("MBOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sim.
        /// </summary>
        public static string MBYesText {
            get {
                return ResourceManager.GetString("MBYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to novos &apos;posts&apos; disponíveis.
        /// </summary>
        public static string NewPosts {
            get {
                return ResourceManager.GetString("NewPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sem ligação à internet.
        /// </summary>
        public static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to desligado.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ligado.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fotos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avalie o Xá das 5 WindowsPhone.
        /// </summary>
        public static string RateReminder_MessageBox_Content {
            get {
                return ResourceManager.GetString("RateReminder_MessageBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to não mostrar esta alerta novament.
        /// </summary>
        public static string RateReminder_MessageBox_SkipFurtherRemindersMessage {
            get {
                return ResourceManager.GetString("RateReminder_MessageBox_SkipFurtherRemindersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avalie esta app.
        /// </summary>
        public static string RateReminder_MessageBox_Title {
            get {
                return ResourceManager.GetString("RateReminder_MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refrescar.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurar.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partilhar.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a app.
        /// </summary>
        public static string TheApp {
            get {
                return ResourceManager.GetString("TheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to versão.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
